# Generated by Django 5.0.1 on 2024-02-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
